services:
  broker:
    image: apache/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
    networks:
      - ninoverse-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nino
      - POSTGRES_PASSWORD=nino
    #   - POSTGRES_DB=ninoverse
    volumes:
      - postgres-data-ninoverse:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - ninoverse-network

  # ninoverse:
  #   image: ninoverse:0.0.1
  #   ports:
  #     - "3000:7878"
  #   environment:
  #     - APP__PORT=7878
  #     - APP__HOST=localhost
  #     - APP__DATABASE__HOST=postgres
  #     - APP__DATABASE__PORT=5432
  #     - APP__DATABASE__USER=nino
  #     - APP__DATABASE__PASSWORD=nino
  #     - APP__DATABASE__DATABASE=ninoverse
  #     - APP__DATABASE__POOL_SIZE=25
  #     - APP__KAFKA__BROKER=broker:9092
  #     - APP__KAFKA__TOPICS=ninoverse:1:1
  #   networks:
  #     - ninoverse-network

networks:
  ninoverse-network:
    driver: bridge

volumes:
  postgres-data-ninoverse: