services:
  postgres:
    image: postgres:19beta3-trixie
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nino
      - POSTGRES_PASSWORD=nino
    volumes:
      - ninoverse-volume-postgres-data:/var/lib/postgresql
    networks:
      - ninoverse-network

networks:
  ninoverse-network:
    driver: bridge

volumes:
  ninoverse-volume-postgres-data:
