services:
  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    command:
      - "--retentionPeriod=14d"
      - "--httpListenAddr=:9428"
    volumes:
      - victorialogs-data:/victoria-logs-data
    networks:
      - ninoverse-network