services:
  grafana:
    image: grafana/grafana:13.2.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=victoriametrics-logs-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - ninoverse-network

volumes:
  grafana-data:
