name: k3s

services:
  k3s-server:
    image: rancher/k3s:v1.36.4-k3s1
    container_name: k3s-server
    command:
      - server
      - --tls-san=k3s-server
      - "--kube-apiserver-arg=oidc-issuer-url=https://auth.nicolapasqualini.it/oauth2/openid/headlamp"
      - "--kube-apiserver-arg=oidc-client-id=headlamp"
      - "--kube-apiserver-arg=oidc-username-claim=preferred_username"
      - "--kube-apiserver-arg=oidc-username-prefix=oidc:"
      - "--kube-apiserver-arg=oidc-groups-claim=groups"
      - "--kube-apiserver-arg=oidc-groups-prefix=oidc:"
      - "--kube-apiserver-arg=oidc-signing-algs=ES256"
    tmpfs:
      - /run
      - /var/run
    privileged: true
    restart: always
    environment:
      - K3S_DATASTORE_ENDPOINT=http://etcd:2379
      - K3S_TOKEN=my-super-secret-token
      - K3S_KUBECONFIG_MODE=644
    volumes:
      - k3s-server-data:/var/lib/rancher/k3s
    ports:
      - "6443:6443"
    networks:
      - etcd-backend
      - ninoverse-network
      - k3s-server-network

  k3s-agent:
    image: rancher/k3s:v1.36.4-k3s1
    container_name: k3s-agent
    command: agent
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=my-super-secret-token
    volumes:
      - k3s-agent-data:/var/lib/rancher/k3s
    networks:
      - k3s-server-network
    depends_on:
      - k3s-server

volumes:
  k3s-server-data:
  k3s-agent-data:

networks:
  etcd-backend:
    external: true
  ninoverse-network:
    external: true
  k3s-server-network:
