host: "localhost"
port: 7878

database:
  host: "localhost"
  port: "5432" 
  name: "ninoverse"
  user: "nino"
  password: "nino"
  pool_size: 25

kafka:
  broker: "localhost:9092"
  group_id: "ninoverse"
  topics:
    - "ninoverse:1:1"