host: "localhost"
port: 7878

database:
  host: "localhost"
  port: "5432"
  name: "ninoverse"
  user: "nino"
  password: "nino"
  pool_size: 25
  connection_attempt: 5

kafka:
  broker: "localhost:9092"
  group_id: "ninoverse"
  topics:
    - "ninoverse:1:1"

docker:
  remove_containers_on_shutdown: true
  remove_volumes_on_shutdown: false
  remove_networks_on_shutdown: false
